[package]
name = "libcore"
version = "0.1.0"
authors = ["Hentioe_Cl <me@bluerain.io>"]
edition = "2018"

[dependencies]
reqwest = "0.9.8"
failure = "0.1.5"
scraper = "0.9.0"
lazy_static = "1.2.0"
tree_magic = "0.2.1"
tera = "0.11.20"
serde_derive = "1.0.84"
serde = "1.0.84"
zip = "0.5.0"
walkdir = "2.2.7"
serde_json = "1.0.35"
regex = "1.1.0"
uuid = "0.7"
chrono = "0.4.6"